<a href="https://colab.research.google.com/github/prateekrai8467/Daily-_Python-_training/blob/main/Module2_Activity2_1_NumPy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Course: Data Analytics Using Python (AIL0202)
## Module 2 – Activity 2.1
### NumPy Hands-on Lab (5 Marks)


### Instructions:
- Complete all tasks.
- Run each cell and show outputs.
- Add comments wherever required.
- Submit the completed notebook(PDF) on LMS.

Name:Prateek Rai

Roll No.:BETN1AI25105

COllab Link : https://colab.research.google.com/drive/1Mmvrt1JVE4TCV5QT5tHFhYP9OqRnr4OH


In [ ]:
# Import NumPy
import numpy as np
print('NumPy Version:', np.__version__)


## Task 1: Array Creation(1 Mark)

Create:

1D array of 10 integers

2D array (3×3 matrix)

Identity matrix of size 4

Random array (5×5)

In [31]:
#Create required arrays here
import numpy as np
# 1D array of 10 integers
array_one_d = np.arange(1,11)
print(array_one_d)
print('\n')

# 3x3 matrix
array_three_d=np.array([[1,2,3],[2,3,4],[4,5,6]])
print(array_three_d)
print('\n')

# Identity matrix of size 4
array_identity_matrix = np.eye(4)
print(array_identity_matrix)
print('\n')

# Random 5x5 matrix
random_matrix_five_d= np.random.randint(0,10,(5,5))
print(random_matrix_five_d)
print('\n')

[ 1  2  3  4  5  6  7  8  9 10]


[[1 2 3]
 [2 3 4]
 [4 5 6]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[5 3 7 9 2]
 [3 8 5 7 8]
 [5 2 0 1 6]
 [2 8 0 8 3]
 [9 6 9 0 3]]




## Task 2: Indexing & Slicing (1 Mark)

Given:

A = np.arange(1, 26).reshape(5,5)

Perform:

Extract 2nd row

Extract 3rd column

Extract 2×2 submatrix (center)

Reverse last row

In [17]:
import numpy as np

A = np.arange(1, 26).reshape(5,5)
print(A)
print("\n")

# Extract 2nd row
print(A[1])
print("\n")

# Extract 3rd column
print(A[:2])
print("\n")

# Extract 2x2 center matrix
print(A[1:3,1:3])
print("\n")

# Reverse last row
print(A[-1][::-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[ 6  7  8  9 10]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[[ 7  8]
 [12 13]]


[25 24 23 22 21]


## Task 3: Broadcasting(1 Mark)

Perform broadcasting operations on matrix A created in Task-2.

Add scalar 10 to matrix A

Add vector [1,2,3,4,5] to each row

Normalize matrix values between 0–1

In [35]:
import numpy as np

A = np.arange(1, 26).reshape(5,5)
print(A)

# Perform broadcasting operations here

# Add scalar 10 to matrix
print('\n')
print( A + 10)
print("\n")

# Add vector [1,2,3,4,5] to each row
print( A + np.array([1,2,3,4,5]))
print("\n")

# Normalize matrix between 0 and 1
normalized_A = (A - A.min()) / (A.max() - A.min())
print( normalized_A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


[[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]]


[[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


## Task 4: Vectorized Computation(1 Marks)

Perform element-wise multiplication
Compute dot product
Compute mean, standard deviation

In [28]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

#Element-wise multiplication
print(X*Y)
# Dot product
print(np.dot(X,Y))

# Mean and Standard Deviation
print(f"This is mean of X :{np.mean(X)}" )
print(f"This is mean of Y :{np.mean(Y)}" )
print(f"This is standard deviation of Y :{np.std(X)}" )
print(f"This is standard deviation of Y :{np.std(Y)}" )


[ 5 12 21 32]
70
This is mean of X :2.5
This is mean of Y :6.5
This is standard deviation of Y :1.118033988749895
This is standard deviation of Y :1.118033988749895


Task 5: Mini Case Problem (1 Mark)

Dataset: Student marks (5 students, 3 subjects)

Compute total and average per student

Find topper

Find subject-wise highest score

In [30]:
import numpy as np

marks = np.array([[80,75,90],[60,88,70],[95,92,85],[70,65,60],[88,78,84]])
# Compute totals, averages, topper

totals = np.sum(marks, axis = 1)
print(totals)
print('\n')

averages = np.mean(marks , axis = 1)
print(averages)
print('\n')

topper = np.argmax(totals)
print(topper)
print('\n')

subject_highest = np.max(marks , axis = 0)
print(subject_highest)
print('\n')


[245 218 272 195 250]
[81.66666667 72.66666667 90.66666667 65.         83.33333333]
2
[95 92 90]
